function automatedPlotSaver( autoFigPath, additionalFigParams, options )

arguments
    autoFigPath char
    additionalFigParams char
    options.clearOldFigures double = 0
    options.automatedSaveVectors double = 0
    options.vectorAutoFigPath char
    options.closeFiguresAfterSaving double = 0
    options.suppressRenamingMessages double = 0 %Whether to suppress messages about whether a plot title was renamed for the filename
end

clearOldFigures = options.clearOldFigures;
automatedSaveVectors = options.automatedSaveVectors;
closeFiguresAfterSaving = options.closeFiguresAfterSaving;
suppressRenamingMessages = options.suppressRenamingMessages;

    %--------------------------------------------------------------------------
    
    %Make for loop to save figures
    %Mk 3 (Borrowed from SASIFRAS)
    %if automatedSavePlots == 1
        tic
        disp(['---- COMMENCING AUTOMATED FIGURE SAVING ----'])
        
        if clearOldFigures == 1
            %disp(['-- Clearing old figures --'])
            %oldName = strcat(autoFigPath,'\', progIdent, '*', additionalFigParams, '*.png');
            oldName = strcat(autoFigPath,'\', '*.png'); %Removed progIdent
            oldName = strrep(oldName, '**', '*'); %Quick strrep to convert **'s to *'s (Because otherwise MATLAB complains)
            oldFigList = dir(oldName);
            
            if size(oldFigList,1) > 0
                disp(['-- Old figures detected; Clearing --'])
            end
            
            s = warning('error', 'MATLAB:DELETE:Permission');
            for i = 1:size(oldFigList,1)
                try   
                   delete(strcat([autoFigPath, '\', oldFigList(i).name]));
                        %Note: Theoretically only deletes figures generated by this script
                   %disp(['-- Old workspace save deleted --'])
                catch
                    ['#### Could not delete existing figure ####']
                    error = yes
                end
            end
            if size(oldFigList,1) > 0
                disp(['-- ',num2str(i),' Old figures cleared --'])
            end
        end
        
        
        figList = get(groot, 'Children');
        %figList = findall(groot, 'Type', 'figure');
        figNameTally = 0;
        figFailTally = 0;
        for i = 1:size(figList,1)
            try
                    %Note: If being run post-hoc, it seems reverse indexing might be required for correct figure numbers
                figure(figList(i)) %Select figure
    
                set(gcf, 'Color', 'w');
                set(gcf,'units','normalized','outerposition',[0 0 1 1])
    
                %Save as PNG
                if isempty(figList(i).Name) ~= 1
                    %saveName = strcat(autoFigPath,'\', progIdent, '_Fig_', num2str(figList(i).Number), '_', figList(i).Name ,'.png');
                    thisFigName = figList(i).Name;
                    [thisFigNameSafe, modified] = matlab.lang.makeValidName(figList(i).Name);
                    %Report
                    if modified == 1
                        if ~suppressRenamingMessages
                            disp(['Fig. ',num2str(i),' - "', figList(i).Name, '" renamed "',thisFigNameSafe,'"'])
                        end
                        figNameTally = figNameTally + 1;
                    end
                    %saveName = strcat(autoFigPath,'\', 'Fig_', num2str(figList(i).Number), '_', thisFigNameSafe ,'.png');
                else
                    %saveName = strcat(figPath,'\', progIdent, '_Fig_', num2str(figList(i).Number) ,'.png');
                    thisFigNameSafe = [];
                    %saveName = strcat(autoFigPath,'\', 'Fig_', num2str(figList(i).Number) , additionalFigParams, '.png');
                end
                saveName = strcat(autoFigPath,'\', 'Fig_', num2str(figList(i).Number), '_', thisFigNameSafe, additionalFigParams ,'.png');
                %export_fig(saveName)
                saveas(gcf,saveName,'png')
    
                if automatedSaveVectors == 1
                    %Attempt save as vector if requested
                    %saveName = strcat(vectorAutoFigPath,'\', progIdent, '_Fig_', num2str(figList(i).Number) , additionalFigParams, '.pdf');
                    vecSaveName = strcat(vectorAutoFigPath,'\', 'Fig_', num2str(figList(i).Number) , thisFigNameSafe, additionalFigParams, '.pdf');
                    try
                        saveas(gca,vecSaveName, 'pdf');
                    catch
                        disp(['## Could not vector-save Figure ', num2str(figList(i).Number), ' ##'])
                        figFailTally = figFailTally + 1;
                    end
                end
    
                if closeFiguresAfterSaving == 1
                    close gcf %Saves memory
                end
            catch
            %pause(0.25)
                disp(['## Could not save Figure ', num2str(figList(i).Number), ' ##'])
                figFailTally = figFailTally + 1;
            end
        end
        disp(['---- ', num2str(size(figList,1)), ' OPEN FIGURES SAVED ("',autoFigPath,'") in ',num2str(toc),'s ----'])
        if figFailTally > 0
            disp(['(There were ',num2str(figFailTally),' failures)'])
        end
    %end
    
    %--------------------------------------------------------------------------

end